name: Macos-latest

on:
  push:
    branches: [ master, iotanbo ]
  pull_request:
    branches: [ master, iotanbo ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build cmd/arc/*.go

    - name: Test
      run: go test -v ./...
